:?*:\astrosun::☉
:?*:\astromoon::☽
:?*:\astromercury::☿
:?*:\astrovenus::♀︎
:?*:\astroearth1::♁
:?*:\astroearth2::⊕
:?*:\astromars::♂︎
:?*:\astrojupiter::♃
:?*:\astrosaturn::♄
:?*:\astrouranus1::♅
:?*:\astrouranus2::⛢
:?*:\astroneptune::♆
:?*:\astropluto1::♇
:?*:\astropluto2::⯓
:?*:\astroceres::⚳
:?*:\astropallas::⚴
:?*:\astrojuno::⚵
:?*:\astrovesta::⚶
:?*:\astrochiron::⚷
:?*:\astrohygiea::⯚
:?*:\astropholus::⯛
:?*:\astronessus::⯜
:?*:\astroeris1::⯰
:?*:\astroeris2::⯱
:?*:\astrosedna::⯲
:?*:\astronodeasc::☊
:?*:\astronodedesc::☋
:?*:\astroconj::☌
:?*:\astroopp::☍

:?*:\zodaries::♈
:?*:\zodtaurus::♉
:?*:\zodgemini::♊
:?*:\zodcancer::♋
:?*:\zodleo::♌
:?*:\zodvirgo::♍
:?*:\zodlibra::♎
:?*:\zodscorpio::♏
:?*:\zodsagittarius::♐
:?*:\zodcapricorn::♑
:?*:\zodaquarius::♒
:?*:\zodpisces::♓
:?*:\zodophiuchus::⛎
