:?*:\astrosun::☉
:?*:\astromoon::☽
:?*:\astromercury::☿
:?*:\astrovenus::♀︎
:?*:\astroearth1::⊕
:?*:\astroearth2::♁
:?*:\astromars::♂︎
:?*:\astrojupiter::♃
:?*:\astrosaturn::♄
:?*:\astrouranus1::♅
:?*:\astrouranus2::⛢
:?*:\astroneptune::♆
:?*:\astropluto::♇
:?*:\astroceres::⚳
:?*:\astropallas::⚴
:?*:\astrojuno::⚵
:?*:\astrovesta::⚶
:?*:\astrochiron::⚷
:?*:\astronodeasc::☊
:?*:\astronodedesc::☋
;
:?*:\zodaries::♈
:?*:\zodtaurus::♉
:?*:\zodgemini::♊
:?*:\zodcancer::♋
:?*:\zodleo::♌
:?*:\zodvirgo::♍
:?*:\zodlibra::♎
:?*:\zodscorpio::♏
:?*:\zodsagittarius::♐
:?*:\zodcapricorn::♑
:?*:\zodaquarius::♒
:?*:\zodpisces::♓
:?*:\zodcophiuchus::⛎