:?*:\alpha::α
:?*:\beta::β
:?*:\gamma::γ
:?*:\delta::δ
:?*:\epsilon::ε
:?*:\zeta::ζ
:?*:\eta::η
:?*:\theta::θ
:?*:\iota::ι
:?*:\kappa::κ
:?*:\lambda::λ
:?*:\mu::μ
:?*:\nu::ν
:?*:\xi::ξ
:?*:\omicron::ο
:?*:\pi::π
:?*:\rho::ρ
:?*:\sigma::σ
:?*:\varsigma::ς
:?*:\tau::τ
:?*:\upsilon::υ
:?*:\phi::φ
:?*:\varphi::ϕ
:?*:\chi::χ
:?*:\psi::ψ
:?*:\omega::ω
:?*:\digamma::ϝ
:?*:\heta::ͱ
:?*:\qoppa::ϙ
:?*:\varqoppa::ϟ
:?*:\tsan::ϻ
:?*:\vartsan::ͷ
:?*:\stigma::ϛ
