:?*:\aleph::א
:?*:\beth::ב
:?*:\gimel::ג
:?*:\dalet::ד
:?*:\hei::ה
:?*:\vav::ו
:?*:\zayin::ז
:?*:\heth::ח
:?*:\teth::ט
:?*:\yod::י
:?*:\kaph::כ
:?*:\lamed::ל
:?*:\mem::מ
:?*:\nun::נ
:?*:\samekh::ס
:?*:\ayin::ע
:?*:\pei::פ
:?*:\tsadi::צ
:?*:\qoph::ק
:?*:\resh::ר
:?*:\shin::ש
:?*:\tav::ת
;
:?*:\finkaph::ך
:?*:\finmem::ם
:?*:\finnun::ן
:?*:\finpei::ף
:?*:\fintsadi::ץ